spring.application.name=springboot-jsp-demo
server.port=8080

spring.mvc.view.prefix= /WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Hard code for username and password
login.username=admin@gmail.com
login.password=123456